image: Ubuntu1804  # образ для сборки

branches:
  only:
    - master

build: off

install:
  - java -jar ./artifacts/app-ibank.jar -P:profile=test &

build_script:
  - ps: chmod +x gradlew
  - ps: ./gradlew test --info "-Dselenide.headless=true"

